export const componentCategories = [
  {
    category: '基础组件',
    items: [
      { name: 'QAjaxBar', desc: 'Ajax 加载进度条' },
      { name: 'QAvatar', desc: '头像' },
      { name: 'QBadge', desc: '徽章' },
      { name: 'QBanner', desc: '横幅' },
      { name: 'QBar', desc: '工具栏条' },
      { name: 'QBreadcrumbs', desc: '面包屑导航' },
    ],
  },
  {
    category: '按钮',
    items: [
      { name: 'QBtn', desc: '按钮' },
      { name: 'QBtnGroup', desc: '按钮组' },
      { name: 'QBtnDropdown', desc: '下拉按钮' },
    ],
  },
  {
    category: '卡片与媒体',
    items: [
      { name: 'QCard', desc: '卡片' },
      { name: 'QCarousel', desc: '轮播' },
      { name: 'QChat', desc: '聊天消息' },
      { name: 'QChip', desc: '标签' },
      { name: 'QCircularProgress', desc: '环形进度' },
      { name: 'QColorPicker', desc: '颜色选择器' },
    ],
  },
  {
    category: '对话框与菜单',
    items: [
      { name: 'QDialog', desc: '对话框' },
      { name: 'QEditor', desc: '富文本编辑器' },
      { name: 'QExpansionItem', desc: '展开项' },
      { name: 'QFloatingActionButton', desc: '浮动按钮' },
      { name: 'QMenu', desc: '菜单' },
      { name: 'QPopupEdit', desc: '弹出编辑' },
      { name: 'QPopupProxy', desc: '弹出代理' },
    ],
  },
  {
    category: '表单组件',
    items: [
      { name: 'QInput', desc: '文本输入' },
      { name: 'QSelect', desc: '下拉选择' },
      { name: 'QFile', desc: '文件选择' },
      { name: 'QForm', desc: '表单容器' },
      { name: 'QField', desc: '字段包装器' },
      { name: 'QRadio', desc: '单选' },
      { name: 'QCheckbox', desc: '复选' },
      { name: 'QToggle', desc: '开关' },
      { name: 'QBtnToggle', desc: '按钮开关' },
      { name: 'QOptionGroup', desc: '选项组' },
      { name: 'QSlider', desc: '滑块' },
      { name: 'QRange', desc: '范围滑块' },
      { name: 'QTime', desc: '时间选择' },
      { name: 'QDate', desc: '日期选择' },
    ],
  },
  {
    category: '布局与导航',
    items: [
      { name: 'QImg', desc: '图片' },
      { name: 'QInfiniteScroll', desc: '无限滚动' },
      { name: 'QInnerLoading', desc: '内部加载' },
      { name: 'QIntersection', desc: '交叉观察' },
      { name: 'QKnob', desc: '旋钮' },
      { name: 'QLinearProgress', desc: '线性进度' },
      { name: 'QList', desc: '列表' },
      { name: 'QMarkupTable', desc: '标记表格' },
      { name: 'QNoSsr', desc: '无 SSR' },
      { name: 'QPagination', desc: '分页' },
      { name: 'QParallax', desc: '视差' },
      { name: 'QPullToRefresh', desc: '下拉刷新' },
      { name: 'QRating', desc: '评分' },
      { name: 'QResponsive', desc: '响应式' },
      { name: 'QScrollArea', desc: '滚动区域' },
      { name: 'QSeparator', desc: '分隔线' },
      { name: 'QSkeleton', desc: '骨架屏' },
      { name: 'QSlideItem', desc: '滑动项' },
      { name: 'QSpace', desc: '空间' },
      { name: 'QSpinners', desc: '加载动画' },
      { name: 'QSplitter', desc: '分割器' },
      { name: 'QStepper', desc: '步骤器' },
      { name: 'QTable', desc: '表格' },
      { name: 'QTabs', desc: '标签页' },
      { name: 'QTabPanels', desc: '标签面板' },
      { name: 'QTimeline', desc: '时间线' },
      { name: 'QToolbar', desc: '工具栏' },
      { name: 'QTooltip', desc: '提示' },
      { name: 'QTree', desc: '树形' },
      { name: 'QUploader', desc: '上传' },
      { name: 'QVideo', desc: '视频' },
      { name: 'QVirtualScroll', desc: '虚拟滚动' },
    ],
  },
  {
    category: '观察器',
    items: [
      { name: 'QResizeObserver', desc: '元素尺寸观察' },
      { name: 'QScrollObserver', desc: '滚动观察' },
    ],
  },
]

export const directives = [
  { name: 'v-close-popup', desc: '关闭弹出层' },
  { name: 'v-intersection', desc: '交叉观察指令' },
  { name: 'v-ripple', desc: 'Material 涟漪效果' },
  { name: 'v-mutation', desc: 'DOM 变化观察' },
  { name: 'v-morph', desc: '形变动画' },
  { name: 'v-scroll', desc: '滚动监听' },
  { name: 'v-scroll-fire', desc: '滚动触发' },
  { name: 'v-touch-hold', desc: '长按触摸' },
  { name: 'v-touch-pan', desc: '拖拽触摸' },
  { name: 'v-touch-repeat', desc: '重复触摸' },
  { name: 'v-touch-swipe', desc: '滑动触摸' },
]

export const plugins = [
  { name: 'Addressbar Color', desc: '地址栏颜色' },
  { name: 'App Fullscreen', desc: '全屏' },
  { name: 'App Visibility', desc: '应用可见性' },
  { name: 'Bottom Sheet', desc: '底部弹窗' },
  { name: 'Cookies', desc: 'Cookie 管理' },
  { name: 'Dark', desc: '暗黑模式' },
  { name: 'Dialog', desc: '对话框' },
  { name: 'Loading', desc: '加载' },
  { name: 'Loading Bar', desc: '加载进度条' },
  { name: 'Local/Session Storage', desc: '本地存储' },
  { name: 'Meta', desc: 'HTML Meta 管理' },
  { name: 'Notify', desc: '通知提示' },
]

export const composables = [
  { name: 'useQuasar', desc: '访问 $q 对象' },
  { name: 'useDialogPluginComponent', desc: '对话框组件' },
  { name: 'useFormChild', desc: '表单子组件' },
  { name: 'useMeta', desc: 'Meta 标签管理' },
  { name: 'useHydration', desc: 'SSR 水合' },
  { name: 'useId', desc: '唯一 ID 生成' },
  { name: 'useInterval', desc: '定时器' },
  { name: 'useRenderCache', desc: '渲染缓存' },
  { name: 'useTick', desc: 'DOM 更新回调' },
  { name: 'useTimeout', desc: '超时定时器' },
  { name: 'useSplitAttrs', desc: '属性分离' },
]

export const utils = [
  { name: 'Date Utils', desc: '日期处理' },
  { name: 'Color Utils', desc: '颜色处理' },
  { name: 'DOM Utils', desc: 'DOM 操作' },
  { name: 'Morph Utils', desc: '形变工具' },
  { name: 'Formatter Utils', desc: '格式化工具' },
  { name: 'Scrolling Utils', desc: '滚动工具' },
  { name: 'Type Checking Utils', desc: '类型检查' },
  { name: 'EventBus Util', desc: '事件总线' },
  { name: 'Other Utils', desc: '其他工具' },
]

export const platforms = [
  { name: 'SPA', label: '单页应用' },
  { name: 'SSR', label: '服务端渲染' },
  { name: 'PWA', label: '渐进式 Web 应用' },
  { name: 'BEX', label: '浏览器扩展' },
  { name: 'Mobile', label: '移动应用' },
  { name: 'Electron', label: '桌面应用' },
]

export const cliModes = [
  { mode: 'SPA', name: '单页应用', desc: '客户端路由的响应式网站，适合管理后台和工具类网站。', features: ['客户端路由', 'HMR', '代码分割', '懒加载'] },
  { mode: 'SSR', name: '服务端渲染', desc: '服务端渲染加可选 PWA 客户端接管，兼顾 SEO 和首屏性能。', features: ['服务端渲染', '客户端水合', 'SEO 优化', '中间件'] },
  { mode: 'PWA', name: '渐进式 Web 应用', desc: '可安装、可离线使用的 Web 应用，提供原生应用般的体验。', features: ['Service Worker', '离线缓存', '可安装', '推送通知'] },
  { mode: 'Mobile', name: '移动应用', desc: '通过 Capacitor 或 Cordova 构建 Android/iOS 原生应用。', features: ['Capacitor', 'Cordova', '真机 HMR', '应用商店发布'] },
  { mode: 'Electron', name: '桌面应用', desc: '使用 Electron 构建跨平台桌面应用。', features: ['跨平台', '预加载脚本', '无边框窗口', '安全策略'] },
  { mode: 'BEX', name: '浏览器扩展', desc: '开发 Chrome/Firefox/Edge 浏览器扩展。', features: ['多浏览器', '后台脚本', '内容脚本', 'Bridge 通信'] },
]
